baseURL = "https://releases.aspose.com"

languageCode = "en-us"
title = "Releases - aspose.com"
theme =  "downloads-common-theme"
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreErrors = ["error-disable-taxonomy"]
[params]
    # googleAnalytics = ""
    # googletagmanager = ""
     backendURL = "https://releases.admin.aspose.com"
     dynamicmenuid = "aspose-en"
     faviconfolder = "aspose"
     contentsection = "com"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[outputs]
  home= ["HTML", "JSON"]

[deployment]

[[deployment.targets]]
name = "Prod"
URL = "s3://releases.aspose.com/?region=us-west-2"

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^.+\\.(xml)$"
contentType = "application/xml"
gzip = true
force = true      